"""Execution logic for scanning nearby Wi-Fi networks with airodump-ng."""

from __future__ import annotations

import csv
import os
import shutil
import signal
import subprocess
import tempfile
from pathlib import Path
from typing import Any

from tools.helpers import (
    capture_managed_restore_context,
    ensure_interface_mode,
    restore_managed_connection,
    run_command,
    utc_now_iso,
)

AIRODUMP_CSV_SUFFIX = "-01.csv"
NOT_ASSOCIATED_BSSID = "(not associated)"


def parse_bool(value: str) -> bool:
    """Convert a normalized string boolean to a Python bool."""
    return value.lower() == "true"


def tail_text(value: str, max_chars: int = 1200) -> str:
    """Keep the last part of a command output so errors stay readable."""
    if len(value) <= max_chars:
        return value
    return value[-max_chars:]


def sanitize_csv_value(value: str | None) -> str:
    """Trim whitespace from a CSV cell and normalize empty values."""
    if value is None:
        return ""
    return value.strip()


def parse_int(value: str | None) -> int | None:
    """Parse an integer cell from the CSV output."""
    normalized_value = sanitize_csv_value(value)
    if normalized_value == "":
        return None

    try:
        return int(normalized_value)
    except ValueError:
        return None


def channel_to_frequency_band(channel: int | None) -> str:
    """Infer the Wi-Fi band from the channel number."""
    if channel is None:
        return "unknown"
    if 1 <= channel <= 14:
        return "2.4"
    return "5"


def normalize_security(privacy: str, auth: str) -> str:
    """Build a frontend-friendly security summary from privacy/auth fields."""
    normalized_privacy = privacy.upper()
    normalized_auth = auth.upper()
    privacy_tokens = set(normalized_privacy.split())

    if normalized_privacy in {"OPN", "OPEN"}:
        return "OPEN"
    if "WEP" in normalized_privacy:
        return "WEP"
    if "WPA3" in normalized_privacy:
        return "WPA3"
    if "WPA2" in privacy_tokens and "WPA" in privacy_tokens:
        return "WPA/WPA2"
    if "WPA2" in privacy_tokens:
        return "WPA2"
    if "WPA" in privacy_tokens:
        return "WPA"
    if normalized_auth:
        return normalized_auth
    if normalized_privacy:
        return normalized_privacy
    return "UNKNOWN"


def build_airodump_command(
    interface: str,
    band: str,
    output_prefix: Path,
) -> list[str]:
    """Build the airodump-ng command for the requested scan profile."""
    command = [
        "airodump-ng",
        "--write",
        str(output_prefix),
        "--output-format",
        "csv",
    ]

    if band == "2.4":
        command.extend(["--band", "bg"])
    elif band == "5":
        command.extend(["--band", "a"])

    command.append(interface)
    return command


def stop_capture_process(process: subprocess.Popen[str]) -> None:
    """Stop airodump-ng trying SIGINT first so it flushes output files."""
    if process.poll() is not None:
        return

    try:
        os.killpg(process.pid, signal.SIGINT)
        process.wait(timeout=5)
    except subprocess.TimeoutExpired:
        try:
            os.killpg(process.pid, signal.SIGTERM)
            process.wait(timeout=5)
        except subprocess.TimeoutExpired:
            os.killpg(process.pid, signal.SIGKILL)
            process.wait(timeout=5)
    except ProcessLookupError:
        return


def parse_airodump_csv(csv_path: Path, include_hidden: bool) -> tuple[list[dict[str, Any]], list[dict[str, Any]]]:
    """Parse the AP and station sections generated by airodump-ng in CSV format."""
    with csv_path.open("r", encoding="utf-8", newline="") as csv_file:
        reader = csv.reader(csv_file)
        section = None
        networks: list[dict[str, Any]] = []
        clients: list[dict[str, Any]] = []

        for row in reader:
            normalized_row = [sanitize_csv_value(cell) for cell in row]
            if not any(normalized_row):
                continue

            first_cell = normalized_row[0]
            if first_cell == "BSSID":
                section = "networks"
                continue
            if first_cell == "Station MAC":
                section = "clients"
                continue

            if section == "networks":
                bssid = normalized_row[0]
                privacy = normalized_row[5]
                cipher = normalized_row[6]
                auth = normalized_row[7]
                signal = parse_int(normalized_row[8])
                beacons = parse_int(normalized_row[9]) or 0
                channel = parse_int(normalized_row[3])
                essid = normalized_row[13]
                is_hidden = essid == ""

                if is_hidden and not include_hidden:
                    continue

                networks.append(
                    {
                        "bssid": bssid,
                        "ssid": essid,
                        "is_hidden": is_hidden,
                        "channel": channel,
                        "frequency_band": channel_to_frequency_band(channel),
                        "signal": signal,
                        "security": normalize_security(privacy, auth),
                        "privacy": privacy,
                        "cipher": cipher,
                        "auth": auth,
                        "beacons": beacons,
                        "clients_count": 0,
                    }
                )

            elif section == "clients":
                station_mac = normalized_row[0]
                signal = parse_int(normalized_row[3])
                packets = parse_int(normalized_row[4]) or 0
                associated_bssid = normalized_row[5] or None
                is_associated = associated_bssid not in {None, "", NOT_ASSOCIATED_BSSID}
                probed_essids = [
                    sanitize_csv_value(cell)
                    for cell in normalized_row[6:]
                    if sanitize_csv_value(cell) != ""
                ]

                clients.append(
                    {
                        "station_mac": station_mac,
                        "associated_bssid": associated_bssid if is_associated else None,
                        "is_associated": is_associated,
                        "signal": signal,
                        "packets": packets,
                        "probed_essids": probed_essids,
                    }
                )

    clients_per_bssid: dict[str, int] = {}
    for client in clients:
        associated_bssid = client["associated_bssid"]
        if associated_bssid:
            clients_per_bssid[associated_bssid] = clients_per_bssid.get(associated_bssid, 0) + 1

    for network in networks:
        network["clients_count"] = clients_per_bssid.get(network["bssid"], 0)

    return networks, clients


def scan_wifi_networks_execute(input: dict[str, Any]) -> dict[str, Any]:
    """Execute the Wi-Fi scan using airodump-ng and return CSV + normalized output."""
    requested_interface = str(input["interface"])
    scan_seconds = int(str(input["scan_seconds"]))
    band = str(input["band"])
    include_hidden = parse_bool(str(input["include_hidden"]))

    if shutil.which("airodump-ng") is None:
        raise RuntimeError(
            "The 'airodump-ng' binary is not available in PATH. "
            "Install aircrack-ng before using this tool."
        )

    restore_context = capture_managed_restore_context(requested_interface)

    try:
        interface_details = ensure_interface_mode(requested_interface, "monitor")
        interface = interface_details["resolved_interface"]
        interface_snapshot = run_command(["iw", "dev"], check=False).stdout.strip()

        with tempfile.TemporaryDirectory(prefix="wifitest_scan_") as temp_dir:
            output_prefix = Path(temp_dir) / "scan"
            csv_path = Path(f"{output_prefix}{AIRODUMP_CSV_SUFFIX}")
            command = build_airodump_command(interface, band, output_prefix)

            process = subprocess.Popen(
                command,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                text=True,
                start_new_session=True,
            )

            stdout_text = ""
            stderr_text = ""

            try:
                stdout_text, stderr_text = process.communicate(timeout=scan_seconds)
            except subprocess.TimeoutExpired:
                stop_capture_process(process)
                stdout_text, stderr_text = process.communicate()

            if not csv_path.exists():
                raise RuntimeError(
                    "airodump-ng did not generate the expected CSV output file. "
                    "Make sure the wireless interface is in monitor mode and can capture traffic. "
                    f"Command: {' '.join(command)} | returncode={process.returncode} | "
                    f"stderr={tail_text(stderr_text.strip()) or '<empty>'} | "
                    f"stdout={tail_text(stdout_text.strip()) or '<empty>'}"
                )

            raw_csv = csv_path.read_text(encoding="utf-8")
            networks, clients = parse_airodump_csv(csv_path, include_hidden)
    finally:
        restore_managed_connection(requested_interface, restore_context)

    raw_text = raw_csv
    if len(networks) == 0:
        diagnostic = [
            "",
            "--- WIFITEST DIAGNOSTIC ---",
            f"requested_interface={requested_interface}",
            f"resolved_interface={interface}",
            "iw_dev_snapshot:",
            interface_snapshot or "<empty>",
            f"airodump_stdout={tail_text(stdout_text.strip()) or '<empty>'}",
            f"airodump_stderr={tail_text(stderr_text.strip()) or '<empty>'}",
        ]
        raw_text = raw_csv + "\n".join(diagnostic)

    return {
        "raw_text": raw_text,
        "normalized": {
            "interface": interface,
            "requested_interface": requested_interface,
            "required_mode": "monitor",
            "scan_seconds": scan_seconds,
            "band": band,
            "include_hidden": include_hidden,
            "networks_count": len(networks),
            "clients_count": len(clients),
            "networks": networks,
            "clients": clients,
            "completed_at": utc_now_iso(),
        },
    }
